services:
  bx.backend:
    image: ${DOCKER_REGISTRY-}bxbackend
    container_name: Backend
    build:
      context: .
      dockerfile: BX.Backend/Dockerfile
    depends_on:
      - SQLServerDB
    ports:
    - "8080:8080"
    - "8081:8081"
    networks:
    - app-containers-network
  SQLServerDB:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SQL_Server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password12345!
    ports:
      - "1433:1433"
    networks:
    - app-containers-network

  bx.frontend:
    image: ${DOCKER_REGISTRY-}bxfrontend
    container_name: Frontend
    build:
      context: .
      dockerfile: BX.Frontend/Dockerfile
    depends_on:
    - SQLServerDB
    ports:
     - "8084:8084"
     - "8085:8085" 
    networks:
    - app-containers-network
    

networks:
  app-containers-network:
    driver: bridge  
