services:
  bx.backend:
    image: ${DOCKER_REGISTRY-}bxbackend
    # environment: 
    #   - BuildXpertDB="Data Source=SQL_Server,1433;Database=BuildExpertDB;Integrated Security=false;User Id=sa;Password=password12345!;TrustServerCertificate=true;"
    build:
      context: .
      dockerfile: BX.Backend/Dockerfile
    depends_on:
      - SQLServerDB
    ports:
    - "8080:8080"
    - "8081:8081"
    networks:
    - app-containers-network
  SQLServerDB:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SQL_Server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password12345!
    ports:
      - "1433:1433"
    networks:
    - app-containers-network

networks:
  app-containers-network:
    driver: bridge  